version: '3'

services:
  zoo1:
    image: zookeeper:3.4.11
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: "server.1=zoo1:2888:3888"
    volumes:
      - ~/jalgoarena/zookeeper/zoo1/data:/data
      - ~/jalgoarena/zookeeper/zoo1/datalog:/datalog
    network_mode: host

  kafka1:
    image: confluentinc/cp-kafka:4.0.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ~/jalgoarena/kafka/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
    network_mode: host

  kafka2:
    image: confluentinc/cp-kafka:4.0.1
    hostname: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9093"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ~/jalgoarena/kafka/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zoo1
    network_mode: host

  kafka3:
    image: confluentinc/cp-kafka:4.0.1
    hostname: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9094"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ~/jalgoarena/kafka/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zoo1
    network_mode: host

  eureka:
    image: spolnik/jalgoarena-eureka:2.0.0
    ports:
      - "5000:5000"
    network_mode: host

  api:
    image: spolnik/jalgoarena-api:2.0.1
    ports:
      - "5001:5001"
    depends_on:
      - eureka
    network_mode: host

  problems:
    image: spolnik/jalgoarena-problems:2.0.0
    ports:
      - "5002:5002"
    depends_on:
      - eureka
    network_mode: host

  auth:
    image: spolnik/jalgoarena-auth:2.0.0
    ports:
      - "5003:5003"
    volumes:
      - ~/jalgoarena/users:/app/UserDetailsStore
    depends_on:
      - eureka
    network_mode: host

  submissions:
    image: spolnik/jalgoarena-submissions:2.0.0
    ports:
      - "5004:5004"
    volumes:
      - ~/jalgoarena/submissions:/app/SubmissionsStore
    depends_on:
      - api
      - auth
      - kafka1
      - kafka2
      - kafka3
    network_mode: host

  events:
    image: spolnik/jalgoarena-events:2.0.0
    ports:
      - "5005:5005"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    network_mode: host

  ranking:
    image: spolnik/jalgoarena-ranking:2.0.0
    ports:
      - "5006:5006"
    volumes:
      - ~/jalgoarena/ranking:/app/RankingStore
    depends_on:
      - api
      - auth
      - kafka1
      - kafka2
      - kafka3
    network_mode: host

  queue:
    image: spolnik/jalgoarena-queue:2.0.0
    ports:
      - "5007:5007"
    depends_on:
      - api
      - auth
      - kafka1
      - kafka2
      - kafka3
    network_mode: host

  judge:
    image: spolnik/jalgoarena-judge:2.0.0
    deploy:
      replicas: 1
    ports:
      - "5008:5008"
    depends_on:
      - api
      - auth
      - kafka1
      - kafka2
      - kafka3
    network_mode: host