version: '3.5'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "submissions:6:2,results:2:2,events:2:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
      - eureka

  kafka2:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9093"
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
      - eureka

  kafka3:
    image: wurstmeister/kafka:latest
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka4:9094"
      KAFKA_LISTENERS: "PLAINTEXT://:9094"
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
      - eureka

  eureka:
    image: spolnik/jalgoarena-eureka:2.0.1
    ports:
      - "5000:5000"

  api:
    image: spolnik/jalgoarena-api:2.0.1
    ports:
      - "5001:5001"
    depends_on:
      - eureka

  problems:
    image: spolnik/jalgoarena-problems:2.0.0
    ports:
      - "5002:5002"
    depends_on:
      - eureka

  auth:
    image: spolnik/jalgoarena-auth:2.0.0
    ports:
      - "5003:5003"
#    volumes:
#      - ~/jalgoarena/users:/app/UserDetailsStore
    depends_on:
      - eureka

  submissions:
    image: spolnik/jalgoarena-submissions:2.0.0
    ports:
      - "5004:5004"
#    volumes:
#      - ~/jalgoarena/submissions:/app/SubmissionsStore
    depends_on:
      - api
      - auth
      - kafka1
      - kafka2
      - kafka3

  events:
    image: spolnik/jalgoarena-events:2.0.0
    ports:
      - "5005:5005"
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  ranking:
    image: spolnik/jalgoarena-ranking:2.0.1
    ports:
      - "5006:5006"
#    volumes:
#      - ~/jalgoarena/ranking:/app/RankingStore
    depends_on:
      - api
      - auth
      - kafka1
      - kafka2
      - kafka3

  queue:
    image: spolnik/jalgoarena-queue:2.0.0
    ports:
      - "5007:5007"
    depends_on:
      - api
      - auth
      - kafka1
      - kafka2
      - kafka3

  judge:
    image: spolnik/jalgoarena-judge:2.0.0
    deploy:
      replicas: 1
    ports:
      - "5008:5008"
    depends_on:
      - api
      - auth
      - kafka1
      - kafka2
      - kafka3

  ui:
    image: spolnik/jalgoarena-ui:2.0.2
    ports:
      - "3000:3000"
    depends_on:
      - api
      - events
